@startuml
'https://plantuml.com/sequence-diagram
skin rose
autonumber

box Rob ATM (F03)
    actor "Player" as player
    participant ":Game" as game
end box

activate player
player -> game : beginContact(Player, ATM)
activate game

opt player leaves proximity
    player -> game: endContact(Player, ATM)
    game --> player: Robbery not initiated
end


game --> player : ATM Robbed
deactivate game

@enduml
