name: Generate UML Diagrams
on:
    push:
        paths:
            - '**.puml'
jobs:
    ci:
        runs-on: ubuntu-latest
        env:
            UML_FILES: ".puml"
        steps:
            -   name: Checkout Source
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   uses: ts-graphviz/setup-graphviz@v1
            -   name: Get changed UML files
                id: getfile
                run: |
                    echo "::set-output name=files::$(git diff-tree -r --no-commit-id --name-only ${{ github.sha }} | grep '.puml' | xargs)"
            -   name: UML files considered echo output
                run: |
                    echo ${{ steps.getfile.outputs.files }}
            -   run: wget --no-verbose https://downloads.sourceforge.net/project/plantuml/plantuml.jar
            -   run: java -jar plantuml.jar -v -tsvg ${{ steps.getfile.outputs.files }}
            -   uses: EndBug/add-and-commit@v7
                with:
                    message: 'Generate SVG for PlantUML'
                    add: '*'
                    push: false
                    author_name: UML Bot
                    author_email: uml@bot.ci.alexander.dk
            -   name: Push changes
                uses: ad-m/github-push-action@master
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    branch: ${{ github.ref }}
